from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field
from typing import Dict, Any
import asyncio
import uuid
import time
from fpdf import FPDF
import os

# -----------------------------
# FastAPI setup
# -----------------------------
app = FastAPI(title="Nextify Backend MVP")

# Allow your GH Pages origin while testing locally
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # tighten later (e.g., ["https://donnaoftadeh.github.io"])
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -----------------------------
# In-memory job store (MVP)
# -----------------------------
class Submission(BaseModel):
    journey_type: str = Field(..., regex="^(company|industry|product|idea)$")
    payload: Dict[str, Any] = Field(..., description="Raw form fields from the page")

JOBS: Dict[str, Dict[str, Any]] = {}
PDF_DIR = os.path.join("data", "pdf")
os.makedirs(PDF_DIR, exist_ok=True)

STEPS = [
    "Parse Submission",
    "Scope & Sanity Checks",
    "Initial Research",
    "Synthesis & Outline",
    "Write Report (PDF)"
]

# -----------------------------
# Utilities
# -----------------------------
def _pdf_path(job_id: str) -> str:
    return os.path.join(PDF_DIR, f"{job_id}.pdf")

def generate_pdf(job_id: str, submission: Submission) -> str:
    """Very simple PDF generator (placeholder for your real agent output)."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Nextify — Innovation Brief", ln=True)
    pdf.ln(4)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Job ID: {job_id}", ln=True)
    pdf.cell(0, 8, f"Journey Type: {submission.journey_type}", ln=True)
    pdf.ln(4)

    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, "Submitted Fields:", ln=True)

    pdf.set_font("Arial", "", 12)
    for k, v in submission.payload.items():
        pdf.multi_cell(0, 7, f"- {k}: {v}")

    pdf.ln(6)
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, "Notes:", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(
        0,
        7,
        "This is a placeholder report generated by the backend MVP. "
        "In the next step, your multi-agent pipeline will produce this content, "
        "and we’ll stream status updates from each agent."
    )

    path = _pdf_path(job_id)
    pdf.output(path)
    return path

async def run_job(job_id: str, submission: Submission):
    """Simulate multi-step processing and produce a PDF."""
    job = JOBS[job_id]
    total = len(STEPS)

    for i, step in enumerate(STEPS, start=1):
        job["status"] = "running"
        job["step"] = step
        job["progress"] = int((i - 1) / total * 100)
        job["message"] = f"{step}…"
        # Simulate work
        await asyncio.sleep(1.2)

    # Final step: generate PDF
    job["message"] = "Writing PDF…"
    await asyncio.sleep(0.8)
    pdf_path = generate_pdf(job_id, submission)
    job["pdf_path"] = pdf_path

    job["progress"] = 100
    job["step"] = "Complete"
    job["status"] = "done"
    job["message"] = "Report ready."

# -----------------------------
# API endpoints
# -----------------------------
@app.post("/api/submit")
async def submit(submission: Submission):
    """Accepts a submission, starts a background task, returns a job_id."""
    job_id = str(uuid.uuid4())
    JOBS[job_id] = {
        "created_at": time.time(),
        "status": "queued",
        "step": "Queued",
        "progress": 0,
        "message": "Job queued.",
        "pdf_path": None,
        "journey_type": submission.journey_type,
    }
    # Fire and forget
    asyncio.create_task(run_job(job_id, submission))
    return {"job_id": job_id}

@app.get("/api/status/{job_id}")
async def status(job_id: str):
    job = JOBS.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return {
        "job_id": job_id,
        "status": job["status"],
        "step": job["step"],
        "progress": job["progress"],
        "message": job["message"],
        "ready": job["status"] == "done",
    }

@app.get("/api/result/{job_id}")
async def result(job_id: str):
    job = JOBS.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if job["status"] != "done" or not job["pdf_path"]:
        return JSONResponse({"error": "Result not ready"}, status_code=202)
    return FileResponse(job["pdf_path"], media_type="application/pdf", filename=f"{job_id}.pdf")

@app.get("/")
async def root():
    return {"ok": True, "service": "Nextify Backend MVP"}
