# app/templates.py

from textwrap import dedent
from typing import Dict

# If you already have per-journey templates, switch to a dict like:
# FINAL_MD_TEMPLATE_BY_JOURNEY = {
#   "company": "...",
#   "industry": "...",
#   "product": "...",
#   "idea": "...",
# }

FINAL_MD_TEMPLATE = dedent("""
# Innovation Brief

**Entry:** {entry}
**Benchmark:** {benchmark}
**Region(s):** {regions}
**Segment(s):** {segments}

---

## Summary
{summary}

## Benchmark / Industry Insights
{insights}

## Strategic Options
{options_md}

## Recommended Plan
{recommended_md}

### OKRs
{okrs_md}

### 90-Day Plan
{plan_md}

## MVP Scope & Validation
{mvp_md}

## Risks & Next Questions
{risks_md}

---
*Generated by Nextify Agents*
""").strip()


def render_final_markdown(entry: str, payload: Dict, pieces: Dict) -> str:
    """Renders the final markdown using your template (can be replaced 1:1)."""
    bench = payload.get("bench_company") or payload.get("company_name") or "N/A"
    regions = payload.get("region") or payload.get("target_region") or "N/A"
    segments = (
        payload.get("segment")
        or payload.get("target_segment")
        or payload.get("segment_notes")
        or "N/A"
    )

    # pieces should contain keys set by your Writer agent
    return FINAL_MD_TEMPLATE.format(
        entry=entry,
        benchmark=bench,
        regions=regions,
        segments=segments,
        summary=pieces.get("summary", "").strip(),
        insights=pieces.get("insights", "").strip(),
        options_md=pieces.get("options_md", "").strip(),
        recommended_md=pieces.get("recommended_md", "").strip(),
        okrs_md=pieces.get("okrs_md", "").strip(),
        plan_md=pieces.get("plan_md", "").strip(),
        mvp_md=pieces.get("mvp_md", "").strip(),
        risks_md=pieces.get("risks_md", "").strip(),
    )
